<a href="https://colab.research.google.com/github/Dennis123455555555555555555555/Linear-Algebra58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. 

In [7]:
import numpy as np
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system:

In [6]:
import numpy as np

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


Problem 3. Consider the matrix, 

In [5]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print (A)

w,v = np.linalg.eig(A)
print("The eigenvalue is/are",w)
print("The rigt eigenvectors are",v)


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue is/are [-1.  3.  2.]
The rigt eigenvectors are [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
