<a href="https://colab.research.google.com/github/Dennis123455555555555555555555/Linear-Algebra58020/blob/main/Matrix_and_Its_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#Sum A+B
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [2]:
#Subtraction A-B
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [4]:
#subraction B-B
a = np.array ([[6,-3],[2,3]])
b = np.array ([[6,-3],[2,3]])
print(a-b)

[[0 0]
 [0 0]]
