<a href="https://colab.research.google.com/github/Dennis123455555555555555555555/Linear-Algebra58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5 

In [11]:
import numpy as np

square_matrix = np.identity(5)

print(f'Square Matrix whose length is 5: \n{square_matrix}')

Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [12]:
import numpy as np

A = np.array([[1,2,3,4,5],[0,6,7,8,9],[0,0,10,11,12],[0,0,0,13,14],[0,0,0,0,15]])
print(A)

[[ 1  2  3  4  5]
 [ 0  6  7  8  9]
 [ 0  0 10 11 12]
 [ 0  0  0 13 14]
 [ 0  0  0  0 15]]


Question 3. Create a Python code that displays a square matrix which is symmetrical

In [14]:
import numpy as np

square_matrix = np.array ([[6,7,8,9,10],
[7,6,7,8,9],
[8,7,6,7,8],
[9,8,7,6,7],
[10,9,8,7,6]])
#prints a square matrix which is symmetrical

print('A square matrix which is symmetrical')
print(square_matrix)

A square matrix which is symmetrical
[[ 6  7  8  9 10]
 [ 7  6  7  8  9]
 [ 8  7  6  7  8]
 [ 9  8  7  6  7]
 [10  9  8  7  6]]


Question 4. What is the inverse of matrix C? Show your solution by python coding

In [2]:
A = np.array([[1,2,3], [2,3,3],[3,4, -2]])
B = np.linalg.inv(A)
print(A)
print(B)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.

In [3]:
A = np.array([[1,2,3], [2,3,3],[3,4, -2]])
B = np.linalg.det(A)
print(A)
print(B)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001


Question 6. Find the roots of the linear equations by showing its python codes 

In [9]:
import numpy as np 

Equations = np.array([[5,4,1],
[10,9,4],
[10,13,15]])

Constants = np.array([[[3.4],
[8.8],
[19.2]]])

roots = np.linalg.inv(Equations) @ Constants

print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
