<a href="https://colab.research.google.com/github/Dennis123455555555555555555555/Linear-Algebra58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [21]:
import numpy as np
C = np.array([[1,1,1,1],[1,1,1,1],[1,2,2,1],[1,2,2,1]])
print(C)

print("(1/2 are the diagonal elements ")
C = np.diagonal([[1,1,1,1],[1,1,1,1],[1,2,2,1],[1,2,2,1]])
print(C)

[[1 1 1 1]
 [1 1 1 1]
 [1 2 2 1]
 [1 2 2 1]]
(1/2 are the diagonal elements 
[1 1 2 1]


Question 2

In [22]:
C = np.array([[1,1,1,1],[1,1,1,1],[1,2,2,1],[1,2,2,1]])
print("values of each element of question 1")
print(C)

print("value of the Elements of question 1.")
letsdoubleit = C*2
print(letsdoubleit)

values of each element of question 1
[[1 1 1 1]
 [1 1 1 1]
 [1 2 2 1]
 [1 2 2 1]]
value of the Elements of question 1.
[[2 2 2 2]
 [2 2 2 2]
 [2 4 4 2]
 [2 4 4 2]]


Question 3

In [13]:
a = np.array ([2,7,4])
b = np.array ([3,9,8])
output = np.cross(a,b)
print(output)

[20 -4 -3]
